// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#warning "This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer headers. Please update your headers."
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#warning "This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers. Please regenerate this file with a newer version of protoc."
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#ifndef PROTOBUF_CONSTEXPR
# if defined(__cplusplus) && __cplusplus >= 201103L
#  define PROTOBUF_CONSTEXPR constexpr
# else
#  define PROTOBUF_CONSTEXPR
# endif
#endif
#ifndef PROTOBUF_NAMESPACE_OPEN
#define PROTOBUF_NAMESPACE_OPEN namespace google { namespace protobuf {
#endif
#ifndef PROTOBUF_NAMESPACE_CLOSE
#define PROTOBUF_NAMESPACE_CLOSE } }
#endif
#ifndef PROTOBUF_NAMESPACE_ID
#define PROTOBUF_NAMESPACE_ID google::protobuf
#endif
#define PROTOBUF_INTERNAL_EXPORT_rpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rpc_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rpc_2eproto;
namespace corpcron {
namespace rpc {
class EchoRequest;
struct EchoRequestDefaultTypeInternal;
extern EchoRequestDefaultTypeInternal _EchoRequest_default_instance_;
class EchoResponse;
struct EchoResponseDefaultTypeInternal;
extern EchoResponseDefaultTypeInternal _EchoResponse_default_instance_;
class ExecuteTaskRequest;
struct ExecuteTaskRequestDefaultTypeInternal;
extern ExecuteTaskRequestDefaultTypeInternal _ExecuteTaskRequest_default_instance_;
class ExecuteTaskResponse;
struct ExecuteTaskResponseDefaultTypeInternal;
extern ExecuteTaskResponseDefaultTypeInternal _ExecuteTaskResponse_default_instance_;
class SubmitTaskRequest;
struct SubmitTaskRequestDefaultTypeInternal;
extern SubmitTaskRequestDefaultTypeInternal _SubmitTaskRequest_default_instance_;
class SubmitTaskResponse;
struct SubmitTaskResponseDefaultTypeInternal;
extern SubmitTaskResponseDefaultTypeInternal _SubmitTaskResponse_default_instance_;
}  // namespace rpc
}  // namespace corpcron
PROTOBUF_NAMESPACE_OPEN
template<> ::corpcron::rpc::EchoRequest* Arena::CreateMaybeMessage<::corpcron::rpc::EchoRequest>(Arena*);
template<> ::corpcron::rpc::EchoResponse* Arena::CreateMaybeMessage<::corpcron::rpc::EchoResponse>(Arena*);
template<> ::corpcron::rpc::ExecuteTaskRequest* Arena::CreateMaybeMessage<::corpcron::rpc::ExecuteTaskRequest>(Arena*);
template<> ::corpcron::rpc::ExecuteTaskResponse* Arena::CreateMaybeMessage<::corpcron::rpc::ExecuteTaskResponse>(Arena*);
template<> ::corpcron::rpc::SubmitTaskRequest* Arena::CreateMaybeMessage<::corpcron::rpc::SubmitTaskRequest>(Arena*);
template<> ::corpcron::rpc::SubmitTaskResponse* Arena::CreateMaybeMessage<::corpcron::rpc::SubmitTaskResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace corpcron {
namespace rpc {

// ===================================================================

class EchoRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corpcron.rpc.EchoRequest) */ {
 public:
  inline EchoRequest() : EchoRequest(nullptr) {}
  ~EchoRequest() override;
  explicit PROTOBUF_CONSTEXPR EchoRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EchoRequest(const EchoRequest& from);
  EchoRequest(EchoRequest&& from) noexcept
    : EchoRequest() {
    *this = ::std::move(from);
  }

  inline EchoRequest& operator=(const EchoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EchoRequest& operator=(EchoRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EchoRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const EchoRequest* internal_default_instance() {
    return reinterpret_cast<const EchoRequest*>(
               &_EchoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EchoRequest& a, EchoRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(EchoRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EchoRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EchoRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EchoRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EchoRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EchoRequest& from) {
    EchoRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EchoRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corpcron.rpc.EchoRequest";
  }
  protected:
  explicit EchoRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:corpcron.rpc.EchoRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2eproto;
};
// -------------------------------------------------------------------

class EchoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corpcron.rpc.EchoResponse) */ {
 public:
  inline EchoResponse() : EchoResponse(nullptr) {}
  ~EchoResponse() override;
  explicit PROTOBUF_CONSTEXPR EchoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EchoResponse(const EchoResponse& from);
  EchoResponse(EchoResponse&& from) noexcept
    : EchoResponse() {
    *this = ::std::move(from);
  }

  inline EchoResponse& operator=(const EchoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline EchoResponse& operator=(EchoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EchoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const EchoResponse* internal_default_instance() {
    return reinterpret_cast<const EchoResponse*>(
               &_EchoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EchoResponse& a, EchoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(EchoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EchoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EchoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EchoResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EchoResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EchoResponse& from) {
    EchoResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EchoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corpcron.rpc.EchoResponse";
  }
  protected:
  explicit EchoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:corpcron.rpc.EchoResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2eproto;
};
// -------------------------------------------------------------------

class SubmitTaskRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corpcron.rpc.SubmitTaskRequest) */ {
 public:
  inline SubmitTaskRequest() : SubmitTaskRequest(nullptr) {}
  ~SubmitTaskRequest() override;
  explicit PROTOBUF_CONSTEXPR SubmitTaskRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SubmitTaskRequest(const SubmitTaskRequest& from);
  SubmitTaskRequest(SubmitTaskRequest&& from) noexcept
    : SubmitTaskRequest() {
    *this = ::std::move(from);
  }

  inline SubmitTaskRequest& operator=(const SubmitTaskRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubmitTaskRequest& operator=(SubmitTaskRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SubmitTaskRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SubmitTaskRequest* internal_default_instance() {
    return reinterpret_cast<const SubmitTaskRequest*>(
               &_SubmitTaskRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SubmitTaskRequest& a, SubmitTaskRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SubmitTaskRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SubmitTaskRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SubmitTaskRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SubmitTaskRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SubmitTaskRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SubmitTaskRequest& from) {
    SubmitTaskRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SubmitTaskRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corpcron.rpc.SubmitTaskRequest";
  }
  protected:
  explicit SubmitTaskRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCronExprFieldNumber = 1,
    kParamsFieldNumber = 2,
    kHandlerFieldNumber = 3,
  };
  // string cron_expr = 1;
  void clear_cron_expr();
  const std::string& cron_expr() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cron_expr(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cron_expr();
  PROTOBUF_NODISCARD std::string* release_cron_expr();
  void set_allocated_cron_expr(std::string* cron_expr);
  private:
  const std::string& _internal_cron_expr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cron_expr(const std::string& value);
  std::string* _internal_mutable_cron_expr();
  public:

  // string params = 2;
  void clear_params();
  const std::string& params() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_params(ArgT0&& arg0, ArgT... args);
  std::string* mutable_params();
  PROTOBUF_NODISCARD std::string* release_params();
  void set_allocated_params(std::string* params);
  private:
  const std::string& _internal_params() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_params(const std::string& value);
  std::string* _internal_mutable_params();
  public:

  // string handler = 3;
  void clear_handler();
  const std::string& handler() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_handler(ArgT0&& arg0, ArgT... args);
  std::string* mutable_handler();
  PROTOBUF_NODISCARD std::string* release_handler();
  void set_allocated_handler(std::string* handler);
  private:
  const std::string& _internal_handler() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_handler(const std::string& value);
  std::string* _internal_mutable_handler();
  public:

  // @@protoc_insertion_point(class_scope:corpcron.rpc.SubmitTaskRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cron_expr_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr params_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr handler_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2eproto;
};
// -------------------------------------------------------------------

class SubmitTaskResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corpcron.rpc.SubmitTaskResponse) */ {
 public:
  inline SubmitTaskResponse() : SubmitTaskResponse(nullptr) {}
  ~SubmitTaskResponse() override;
  explicit PROTOBUF_CONSTEXPR SubmitTaskResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SubmitTaskResponse(const SubmitTaskResponse& from);
  SubmitTaskResponse(SubmitTaskResponse&& from) noexcept
    : SubmitTaskResponse() {
    *this = ::std::move(from);
  }

  inline SubmitTaskResponse& operator=(const SubmitTaskResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubmitTaskResponse& operator=(SubmitTaskResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SubmitTaskResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SubmitTaskResponse* internal_default_instance() {
    return reinterpret_cast<const SubmitTaskResponse*>(
               &_SubmitTaskResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SubmitTaskResponse& a, SubmitTaskResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SubmitTaskResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SubmitTaskResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SubmitTaskResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SubmitTaskResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SubmitTaskResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SubmitTaskResponse& from) {
    SubmitTaskResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SubmitTaskResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corpcron.rpc.SubmitTaskResponse";
  }
  protected:
  explicit SubmitTaskResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTaskIdFieldNumber = 1,
    kErrorFieldNumber = 3,
    kSuccessFieldNumber = 2,
  };
  // string task_id = 1;
  void clear_task_id();
  const std::string& task_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_task_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_task_id();
  PROTOBUF_NODISCARD std::string* release_task_id();
  void set_allocated_task_id(std::string* task_id);
  private:
  const std::string& _internal_task_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_task_id(const std::string& value);
  std::string* _internal_mutable_task_id();
  public:

  // string error = 3;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:corpcron.rpc.SubmitTaskResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2eproto;
};
// -------------------------------------------------------------------

class ExecuteTaskRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corpcron.rpc.ExecuteTaskRequest) */ {
 public:
  inline ExecuteTaskRequest() : ExecuteTaskRequest(nullptr) {}
  ~ExecuteTaskRequest() override;
  explicit PROTOBUF_CONSTEXPR ExecuteTaskRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ExecuteTaskRequest(const ExecuteTaskRequest& from);
  ExecuteTaskRequest(ExecuteTaskRequest&& from) noexcept
    : ExecuteTaskRequest() {
    *this = ::std::move(from);
  }

  inline ExecuteTaskRequest& operator=(const ExecuteTaskRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExecuteTaskRequest& operator=(ExecuteTaskRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExecuteTaskRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExecuteTaskRequest* internal_default_instance() {
    return reinterpret_cast<const ExecuteTaskRequest*>(
               &_ExecuteTaskRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ExecuteTaskRequest& a, ExecuteTaskRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ExecuteTaskRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExecuteTaskRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExecuteTaskRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ExecuteTaskRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ExecuteTaskRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ExecuteTaskRequest& from) {
    ExecuteTaskRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExecuteTaskRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corpcron.rpc.ExecuteTaskRequest";
  }
  protected:
  explicit ExecuteTaskRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTaskIdFieldNumber = 1,
    kParamsFieldNumber = 2,
    kHandlerFieldNumber = 3,
  };
  // string task_id = 1;
  void clear_task_id();
  const std::string& task_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_task_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_task_id();
  PROTOBUF_NODISCARD std::string* release_task_id();
  void set_allocated_task_id(std::string* task_id);
  private:
  const std::string& _internal_task_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_task_id(const std::string& value);
  std::string* _internal_mutable_task_id();
  public:

  // string params = 2;
  void clear_params();
  const std::string& params() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_params(ArgT0&& arg0, ArgT... args);
  std::string* mutable_params();
  PROTOBUF_NODISCARD std::string* release_params();
  void set_allocated_params(std::string* params);
  private:
  const std::string& _internal_params() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_params(const std::string& value);
  std::string* _internal_mutable_params();
  public:

  // string handler = 3;
  void clear_handler();
  const std::string& handler() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_handler(ArgT0&& arg0, ArgT... args);
  std::string* mutable_handler();
  PROTOBUF_NODISCARD std::string* release_handler();
  void set_allocated_handler(std::string* handler);
  private:
  const std::string& _internal_handler() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_handler(const std::string& value);
  std::string* _internal_mutable_handler();
  public:

  // @@protoc_insertion_point(class_scope:corpcron.rpc.ExecuteTaskRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr params_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr handler_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2eproto;
};
// -------------------------------------------------------------------

class ExecuteTaskResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:corpcron.rpc.ExecuteTaskResponse) */ {
 public:
  inline ExecuteTaskResponse() : ExecuteTaskResponse(nullptr) {}
  ~ExecuteTaskResponse() override;
  explicit PROTOBUF_CONSTEXPR ExecuteTaskResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ExecuteTaskResponse(const ExecuteTaskResponse& from);
  ExecuteTaskResponse(ExecuteTaskResponse&& from) noexcept
    : ExecuteTaskResponse() {
    *this = ::std::move(from);
  }

  inline ExecuteTaskResponse& operator=(const ExecuteTaskResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExecuteTaskResponse& operator=(ExecuteTaskResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExecuteTaskResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExecuteTaskResponse* internal_default_instance() {
    return reinterpret_cast<const ExecuteTaskResponse*>(
               &_ExecuteTaskResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ExecuteTaskResponse& a, ExecuteTaskResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ExecuteTaskResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExecuteTaskResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExecuteTaskResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ExecuteTaskResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ExecuteTaskResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ExecuteTaskResponse& from) {
    ExecuteTaskResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExecuteTaskResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "corpcron.rpc.ExecuteTaskResponse";
  }
  protected:
  explicit ExecuteTaskResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 2,
    kErrorFieldNumber = 3,
    kSuccessFieldNumber = 1,
  };
  // string result = 2;
  void clear_result();
  const std::string& result() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_result(ArgT0&& arg0, ArgT... args);
  std::string* mutable_result();
  PROTOBUF_NODISCARD std::string* release_result();
  void set_allocated_result(std::string* result);
  private:
  const std::string& _internal_result() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_result(const std::string& value);
  std::string* _internal_mutable_result();
  public:

  // string error = 3;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:corpcron.rpc.ExecuteTaskResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr result_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rpc_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EchoRequest

// string message = 1;
inline void EchoRequest::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& EchoRequest::message() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.EchoRequest.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EchoRequest::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.EchoRequest.message)
}
inline std::string* EchoRequest::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.EchoRequest.message)
  return _s;
}
inline const std::string& EchoRequest::_internal_message() const {
  return _impl_.message_.Get();
}
inline void EchoRequest::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* EchoRequest::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* EchoRequest::release_message() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.EchoRequest.message)
  return _impl_.message_.Release();
}
inline void EchoRequest::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.EchoRequest.message)
}

// -------------------------------------------------------------------

// EchoResponse

// string message = 1;
inline void EchoResponse::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& EchoResponse::message() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.EchoResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void EchoResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.EchoResponse.message)
}
inline std::string* EchoResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.EchoResponse.message)
  return _s;
}
inline const std::string& EchoResponse::_internal_message() const {
  return _impl_.message_.Get();
}
inline void EchoResponse::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* EchoResponse::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* EchoResponse::release_message() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.EchoResponse.message)
  return _impl_.message_.Release();
}
inline void EchoResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.EchoResponse.message)
}

// -------------------------------------------------------------------

// SubmitTaskRequest

// string cron_expr = 1;
inline void SubmitTaskRequest::clear_cron_expr() {
  _impl_.cron_expr_.ClearToEmpty();
}
inline const std::string& SubmitTaskRequest::cron_expr() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.SubmitTaskRequest.cron_expr)
  return _internal_cron_expr();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitTaskRequest::set_cron_expr(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cron_expr_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.SubmitTaskRequest.cron_expr)
}
inline std::string* SubmitTaskRequest::mutable_cron_expr() {
  std::string* _s = _internal_mutable_cron_expr();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.SubmitTaskRequest.cron_expr)
  return _s;
}
inline const std::string& SubmitTaskRequest::_internal_cron_expr() const {
  return _impl_.cron_expr_.Get();
}
inline void SubmitTaskRequest::_internal_set_cron_expr(const std::string& value) {
  
  _impl_.cron_expr_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitTaskRequest::_internal_mutable_cron_expr() {
  
  return _impl_.cron_expr_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitTaskRequest::release_cron_expr() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.SubmitTaskRequest.cron_expr)
  return _impl_.cron_expr_.Release();
}
inline void SubmitTaskRequest::set_allocated_cron_expr(std::string* cron_expr) {
  if (cron_expr != nullptr) {
    
  } else {
    
  }
  _impl_.cron_expr_.SetAllocated(cron_expr, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cron_expr_.IsDefault()) {
    _impl_.cron_expr_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.SubmitTaskRequest.cron_expr)
}

// string params = 2;
inline void SubmitTaskRequest::clear_params() {
  _impl_.params_.ClearToEmpty();
}
inline const std::string& SubmitTaskRequest::params() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.SubmitTaskRequest.params)
  return _internal_params();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitTaskRequest::set_params(ArgT0&& arg0, ArgT... args) {
 
 _impl_.params_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.SubmitTaskRequest.params)
}
inline std::string* SubmitTaskRequest::mutable_params() {
  std::string* _s = _internal_mutable_params();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.SubmitTaskRequest.params)
  return _s;
}
inline const std::string& SubmitTaskRequest::_internal_params() const {
  return _impl_.params_.Get();
}
inline void SubmitTaskRequest::_internal_set_params(const std::string& value) {
  
  _impl_.params_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitTaskRequest::_internal_mutable_params() {
  
  return _impl_.params_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitTaskRequest::release_params() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.SubmitTaskRequest.params)
  return _impl_.params_.Release();
}
inline void SubmitTaskRequest::set_allocated_params(std::string* params) {
  if (params != nullptr) {
    
  } else {
    
  }
  _impl_.params_.SetAllocated(params, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.params_.IsDefault()) {
    _impl_.params_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.SubmitTaskRequest.params)
}

// string handler = 3;
inline void SubmitTaskRequest::clear_handler() {
  _impl_.handler_.ClearToEmpty();
}
inline const std::string& SubmitTaskRequest::handler() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.SubmitTaskRequest.handler)
  return _internal_handler();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitTaskRequest::set_handler(ArgT0&& arg0, ArgT... args) {
 
 _impl_.handler_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.SubmitTaskRequest.handler)
}
inline std::string* SubmitTaskRequest::mutable_handler() {
  std::string* _s = _internal_mutable_handler();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.SubmitTaskRequest.handler)
  return _s;
}
inline const std::string& SubmitTaskRequest::_internal_handler() const {
  return _impl_.handler_.Get();
}
inline void SubmitTaskRequest::_internal_set_handler(const std::string& value) {
  
  _impl_.handler_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitTaskRequest::_internal_mutable_handler() {
  
  return _impl_.handler_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitTaskRequest::release_handler() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.SubmitTaskRequest.handler)
  return _impl_.handler_.Release();
}
inline void SubmitTaskRequest::set_allocated_handler(std::string* handler) {
  if (handler != nullptr) {
    
  } else {
    
  }
  _impl_.handler_.SetAllocated(handler, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.handler_.IsDefault()) {
    _impl_.handler_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.SubmitTaskRequest.handler)
}

// -------------------------------------------------------------------

// SubmitTaskResponse

// string task_id = 1;
inline void SubmitTaskResponse::clear_task_id() {
  _impl_.task_id_.ClearToEmpty();
}
inline const std::string& SubmitTaskResponse::task_id() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.SubmitTaskResponse.task_id)
  return _internal_task_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitTaskResponse::set_task_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.task_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.SubmitTaskResponse.task_id)
}
inline std::string* SubmitTaskResponse::mutable_task_id() {
  std::string* _s = _internal_mutable_task_id();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.SubmitTaskResponse.task_id)
  return _s;
}
inline const std::string& SubmitTaskResponse::_internal_task_id() const {
  return _impl_.task_id_.Get();
}
inline void SubmitTaskResponse::_internal_set_task_id(const std::string& value) {
  
  _impl_.task_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitTaskResponse::_internal_mutable_task_id() {
  
  return _impl_.task_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitTaskResponse::release_task_id() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.SubmitTaskResponse.task_id)
  return _impl_.task_id_.Release();
}
inline void SubmitTaskResponse::set_allocated_task_id(std::string* task_id) {
  if (task_id != nullptr) {
    
  } else {
    
  }
  _impl_.task_id_.SetAllocated(task_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.task_id_.IsDefault()) {
    _impl_.task_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.SubmitTaskResponse.task_id)
}

// bool success = 2;
inline void SubmitTaskResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool SubmitTaskResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool SubmitTaskResponse::success() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.SubmitTaskResponse.success)
  return _internal_success();
}
inline void SubmitTaskResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void SubmitTaskResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:corpcron.rpc.SubmitTaskResponse.success)
}

// string error = 3;
inline void SubmitTaskResponse::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& SubmitTaskResponse::error() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.SubmitTaskResponse.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SubmitTaskResponse::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.SubmitTaskResponse.error)
}
inline std::string* SubmitTaskResponse::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.SubmitTaskResponse.error)
  return _s;
}
inline const std::string& SubmitTaskResponse::_internal_error() const {
  return _impl_.error_.Get();
}
inline void SubmitTaskResponse::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* SubmitTaskResponse::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* SubmitTaskResponse::release_error() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.SubmitTaskResponse.error)
  return _impl_.error_.Release();
}
inline void SubmitTaskResponse::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.SubmitTaskResponse.error)
}

// -------------------------------------------------------------------

// ExecuteTaskRequest

// string task_id = 1;
inline void ExecuteTaskRequest::clear_task_id() {
  _impl_.task_id_.ClearToEmpty();
}
inline const std::string& ExecuteTaskRequest::task_id() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.ExecuteTaskRequest.task_id)
  return _internal_task_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ExecuteTaskRequest::set_task_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.task_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.ExecuteTaskRequest.task_id)
}
inline std::string* ExecuteTaskRequest::mutable_task_id() {
  std::string* _s = _internal_mutable_task_id();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.ExecuteTaskRequest.task_id)
  return _s;
}
inline const std::string& ExecuteTaskRequest::_internal_task_id() const {
  return _impl_.task_id_.Get();
}
inline void ExecuteTaskRequest::_internal_set_task_id(const std::string& value) {
  
  _impl_.task_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecuteTaskRequest::_internal_mutable_task_id() {
  
  return _impl_.task_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ExecuteTaskRequest::release_task_id() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.ExecuteTaskRequest.task_id)
  return _impl_.task_id_.Release();
}
inline void ExecuteTaskRequest::set_allocated_task_id(std::string* task_id) {
  if (task_id != nullptr) {
    
  } else {
    
  }
  _impl_.task_id_.SetAllocated(task_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.task_id_.IsDefault()) {
    _impl_.task_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.ExecuteTaskRequest.task_id)
}

// string params = 2;
inline void ExecuteTaskRequest::clear_params() {
  _impl_.params_.ClearToEmpty();
}
inline const std::string& ExecuteTaskRequest::params() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.ExecuteTaskRequest.params)
  return _internal_params();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ExecuteTaskRequest::set_params(ArgT0&& arg0, ArgT... args) {
 
 _impl_.params_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.ExecuteTaskRequest.params)
}
inline std::string* ExecuteTaskRequest::mutable_params() {
  std::string* _s = _internal_mutable_params();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.ExecuteTaskRequest.params)
  return _s;
}
inline const std::string& ExecuteTaskRequest::_internal_params() const {
  return _impl_.params_.Get();
}
inline void ExecuteTaskRequest::_internal_set_params(const std::string& value) {
  
  _impl_.params_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecuteTaskRequest::_internal_mutable_params() {
  
  return _impl_.params_.Mutable(GetArenaForAllocation());
}
inline std::string* ExecuteTaskRequest::release_params() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.ExecuteTaskRequest.params)
  return _impl_.params_.Release();
}
inline void ExecuteTaskRequest::set_allocated_params(std::string* params) {
  if (params != nullptr) {
    
  } else {
    
  }
  _impl_.params_.SetAllocated(params, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.params_.IsDefault()) {
    _impl_.params_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.ExecuteTaskRequest.params)
}

// string handler = 3;
inline void ExecuteTaskRequest::clear_handler() {
  _impl_.handler_.ClearToEmpty();
}
inline const std::string& ExecuteTaskRequest::handler() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.ExecuteTaskRequest.handler)
  return _internal_handler();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ExecuteTaskRequest::set_handler(ArgT0&& arg0, ArgT... args) {
 
 _impl_.handler_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.ExecuteTaskRequest.handler)
}
inline std::string* ExecuteTaskRequest::mutable_handler() {
  std::string* _s = _internal_mutable_handler();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.ExecuteTaskRequest.handler)
  return _s;
}
inline const std::string& ExecuteTaskRequest::_internal_handler() const {
  return _impl_.handler_.Get();
}
inline void ExecuteTaskRequest::_internal_set_handler(const std::string& value) {
  
  _impl_.handler_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecuteTaskRequest::_internal_mutable_handler() {
  
  return _impl_.handler_.Mutable(GetArenaForAllocation());
}
inline std::string* ExecuteTaskRequest::release_handler() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.ExecuteTaskRequest.handler)
  return _impl_.handler_.Release();
}
inline void ExecuteTaskRequest::set_allocated_handler(std::string* handler) {
  if (handler != nullptr) {
    
  } else {
    
  }
  _impl_.handler_.SetAllocated(handler, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.handler_.IsDefault()) {
    _impl_.handler_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.ExecuteTaskRequest.handler)
}

// -------------------------------------------------------------------

// ExecuteTaskResponse

// bool success = 1;
inline void ExecuteTaskResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool ExecuteTaskResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool ExecuteTaskResponse::success() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.ExecuteTaskResponse.success)
  return _internal_success();
}
inline void ExecuteTaskResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void ExecuteTaskResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:corpcron.rpc.ExecuteTaskResponse.success)
}

// string result = 2;
inline void ExecuteTaskResponse::clear_result() {
  _impl_.result_.ClearToEmpty();
}
inline const std::string& ExecuteTaskResponse::result() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.ExecuteTaskResponse.result)
  return _internal_result();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ExecuteTaskResponse::set_result(ArgT0&& arg0, ArgT... args) {
 
 _impl_.result_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.ExecuteTaskResponse.result)
}
inline std::string* ExecuteTaskResponse::mutable_result() {
  std::string* _s = _internal_mutable_result();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.ExecuteTaskResponse.result)
  return _s;
}
inline const std::string& ExecuteTaskResponse::_internal_result() const {
  return _impl_.result_.Get();
}
inline void ExecuteTaskResponse::_internal_set_result(const std::string& value) {
  
  _impl_.result_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecuteTaskResponse::_internal_mutable_result() {
  
  return _impl_.result_.Mutable(GetArenaForAllocation());
}
inline std::string* ExecuteTaskResponse::release_result() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.ExecuteTaskResponse.result)
  return _impl_.result_.Release();
}
inline void ExecuteTaskResponse::set_allocated_result(std::string* result) {
  if (result != nullptr) {
    
  } else {
    
  }
  _impl_.result_.SetAllocated(result, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.result_.IsDefault()) {
    _impl_.result_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.ExecuteTaskResponse.result)
}

// string error = 3;
inline void ExecuteTaskResponse::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& ExecuteTaskResponse::error() const {
  // @@protoc_insertion_point(field_get:corpcron.rpc.ExecuteTaskResponse.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ExecuteTaskResponse::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:corpcron.rpc.ExecuteTaskResponse.error)
}
inline std::string* ExecuteTaskResponse::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:corpcron.rpc.ExecuteTaskResponse.error)
  return _s;
}
inline const std::string& ExecuteTaskResponse::_internal_error() const {
  return _impl_.error_.Get();
}
inline void ExecuteTaskResponse::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecuteTaskResponse::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* ExecuteTaskResponse::release_error() {
  // @@protoc_insertion_point(field_release:corpcron.rpc.ExecuteTaskResponse.error)
  return _impl_.error_.Release();
}
inline void ExecuteTaskResponse::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:corpcron.rpc.ExecuteTaskResponse.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc
}  // namespace corpcron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto
